CREATE TABLE "NOTAFISCALITENS"
(
  "CODITEM"  INTEGER NOT NULL,
  "CODNOTA"  INTEGER NOT NULL,
  "CODPRO"  INTEGER,
  "DESCRPRO"  VARCHAR(80),
  "UNIDADE"  VARCHAR(3),
  "QTDE"  DOUBLE PRECISION,
  "VALORTOTAL"  DOUBLE PRECISION,  
  "CODIGOPRODUTOEXTERNO"  VARCHAR(20),
  "VALORUNITARIO"  DOUBLE PRECISION,    
   --PRIMARY KEY ("CODITEM") 
   -- Ajuste: chave primária composta, pois CODITEM não é único globalmente
     PRIMARY KEY (CODITEM, CODNOTA)
);
ALTER TABLE "NOTAFISCALITENS" ADD CONSTRAINT "FK_NOTAFISCALITENS_NOTAFISCAL" FOREIGN KEY ("CODNOTA") REFERENCES "NOTAFISCAL" ("CODNOTA") ON DELETE CASCADE;


INSERT INTO NOTAFISCALITENS(CODITEM, CODNOTA, CODPRO, QTDE, VALORTOTAL, CODIGOPRODUTOEXTERNO, VALORUNITARIO)
VALUES (1, 1, 3552, 1, 270, '442338', 270),
	   (1, 2, 4552, 3, 300, '322164', 100),
	   (1, 3, 2231, 1, 550, '560063', 550),
	   (2, 3, 4552, 1, 100, '322164', 100),
	   (1, 4, NULL, NULL, 0, NULL, 0),
	   (2, 4, NULL, NULL, 0, NULL, 0),
	   (1, 5, NULL, NULL, 0, NULL, 0),
	   (2, 5, NULL, NULL, 0, NULL, 0),
	   (3, 5, NULL, NULL, 0, NULL, 0)

-- Necessário inserir novos dados, para evitar erro de agregação
UPDATE NOTAFISCALITENS
SET QTDE = 1,
    VALORTOTAL = 100
WHERE CODNOTA IN (4,5);
