-- USE [teste_dev] Utilize o banco correto as tabelas

-- Stored procedure que retorna uma lista de Notas Fiscais do mês informado como parâmetro. 
-- EXEC [dbo].SP_BUSCAR_NOTAS_POR_MES 10;


CREATE OR ALTER PROCEDURE SP_BUSCAR_NOTAS_POR_MES
	@MES INT
AS
  BEGIN
      SET NOCOUNT ON;

	  SELECT
		 NF.CODNOTA,
		 NF.NUMNOTA,
		 NF.DTEMISSAO,
		 SUM(NFI.VALORTOTAL) OVER (PARTITION BY NF.CODNOTA) AS VALORTOTALNOTA,
		 NFI.CODITEM,
		 NFI.QTDE,
		 NFI.VALORTOTAL
	FROM NOTAFISCAL NF
	LEFT JOIN NOTAFISCALITENS NFI
			ON NF.CODNOTA = NFI.CODNOTA
	WHERE MONTH(NF.DTEMISSAO) = @MES
	ORDER BY NF.CODNOTA
END